### ISSUE TITLE
Правки по CSS

### ISSUE THREAD

**Issue by 9vit917** [katesavras/tms-react#2]
Классы в CSS называй с маленьким регистром(это как соглашения разработчиков) в дальнейшем разберем методолгии где будет более явно почему это важно) 
https://habr.com/ru/post/303174/
Вот тут кинь свой взгляд на разбор не детальный но +- явный, потом найдем время каждый метод разобрать детальнее

А по заданию, все отлично, молодец)

**Comment by katesavras** [comment]
Хорошо, спасибо) просто там в примере  класс App с большой буквы, я что-то
подумала, что в reacte так принято)

Чт, 18 марта 2021 г. в 10:14, Viktor ***@***.***>:
